# Site settings
title: Estudio Foz
email: estudiofozpersonaltraining@gmail.com
description: Estudio Foz Personal Training - Um conceito especial!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.estudiofoz.com" # the base hostname & protocol for your site
github_username:  estudiotest

# Build settings
markdown: kramdown
